### ISSUE TITLE
Taking attendance error: more than one row returned

### ISSUE THREAD

**Issue by lrcarlisle** [francoisjacquet/rosariosis#115]
We just started our second semester and are not able to enter the attendance.  The error file is below but it has to do with "more than one row returned."  Everything worked fine the first semester but now doesn't.  What could cause this to happen?
------------------------

System: Rosario Student Information System
Date: 08/14/2015 04:44:47
Page: /Modules.php Take Attendance

Failure Notice:  DB Execute Failed.
Additional Info: ERROR:  more than one row returned by a subquery used as an expression

 SELECT '0' AS ID,'Attendance' AS TITLE,0,NULL AS SORT_ORDER
WHERE position(',0,' IN
        (SELECT cp.DOES_ATTENDANCE
        FROM COURSE_PERIODS cp, COURSE_PERIOD_SCHOOL_PERIODS cpsp
        WHERE cp.COURSE_PERIOD_ID=cpsp.COURSE_PERIOD_ID
        AND cpsp.COURSE_PERIOD_SCHOOL_PERIODS_ID='10')
)>0
UNION
        SELECT ID,TITLE,1,SORT_ORDER
        FROM ATTENDANCE_CODE_CATEGORIES
        WHERE SYEAR='2015'
        AND SCHOOL_ID='2'
        AND position(','||ID||',' IN
                (SELECT cp.DOES_ATTENDANCE
                FROM COURSE_PERIODS cp, COURSE_PERIOD_SCHOOL_PERIODS cpsp
                WHERE cp.COURSE_PERIOD_ID=cpsp.COURSE_PERIOD_ID
                AND cpsp.COURSE_PERIOD_SCHOOL_PERIODS_ID='10')
        )>0
        ORDER BY 3,SORT_ORDER,TITLE
Request Array:
Array
(
    [modname] => Attendance/TakeAttendance.php
    [PHPSESSID] => f3ab7b732bc8d9043a37c191ed4842bd
    [day_date] => 14
    [month_date] => AUG
    [year_date] => 2015
)

Session Array:
Array
(
    [locale] => en_US.utf8
    [STAFF_ID] => 33
    [LAST_LOGIN] =>
    [_REQUEST_vars] => Array
        (
            [modname] => Attendance/TakeAttendance.php
            [PHPSESSID] => f3ab7b732bc8d9043a37c191ed4842bd
        )

    [UserSyear] => 2015
    [UserMP] => 18
    [UserSchool] => 2
    [UserCoursePeriod] => 43
    [UserPeriod] => 18
    [SchoolData] => Array
        (
            [SYEAR] => 2015
            [ID] => 2
            [TITLE] => Facultad de Estudios Bíblicos del Uruguay
            [ADDRESS] =>
            [CITY] => Montevideo
            [STATE] =>
            [ZIPCODE] =>
            [PHONE] =>
            [PRINCIPAL] =>
            [WWW_ADDRESS] => febu.org
            [SCHOOL_NUMBER] =>
            [SHORT_NAME] => FEBU
            [REPORTING_GP_SCALE] => 10.000
            [NUMBER_DAYS_ROTATION] =>
            [SCHOOLS_NB] => 2
        )

    [UserCoursePeriodSchoolPeriod] => 10

**Comment by lrcarlisle** [comment]
I may have found the problem.  I just noticed that when I look at the school calendar it says that there is more than one default calendar for this school.  Looking at the database in the "attendance_calendars", I do indeed see two.  Is this the problem we're having?  If so, how can I delete one of them, and how do I know which one to delete?  Both have the same name.  In the program itself, I only see one calendar in the drop down menu so I'm not sure why two are showing up in the database.

**Comment by francoisjacquet** [comment]
@lrcarlisle please confirm the issue has been fixed (https://github.com/francoisjacquet/rosariosis/archive/mobile.zip)
This issue could be related to the one fixed here: https://github.com/francoisjacquet/rosariosis/commit/6fe34ce0450e092fcd969accf2260fdd7de25112

**Comment by lrcarlisle** [comment]
Sorry but after making the changes to the two files, I'm still having the
same problem.


On Sun, Aug 16, 2015 at 3:05 PM, François Jacquet <notifications@github.com>
wrote:

> @lrcarlisle <https://github.com/lrcarlisle> please confirm the issue has
> been fixed (
> https://github.com/francoisjacquet/rosariosis/archive/mobile.zip)
> This issue could be related to the one fixed here: 6fe34ce
> <https://github.com/francoisjacquet/rosariosis/commit/6fe34ce0450e092fcd969accf2260fdd7de25112>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/francoisjacquet/rosariosis/issues/115#issuecomment-131597224>
> .
>



-- 
Larry R. Carlisle
*http://www.carlislefamily.net <http://www.carlislefamily.net>*

**Comment by lrcarlisle** [comment]
I just realized that what I tried that didn't help was the fix that was mentioned: 6fe34ce.  That did not change anything.  However, I just tried first fix you mentioned (modules/Attendance/TakeAttendance) and that did produce results.  I don't get the error message now but two things are occurring:
1) all students' names appear twice in the attendance list
2) no matter what day the course is scheduled for, I have to put in Aug 12.  That is, even if the class met on the 11th or 14th, the names only appear if I put in the date of Aug. 12.  By the way, I'm accessing it as the administrator, not a teacher.
